services:
  # Flask service
  admin:
    container_name: flask-app
    image: python:3.8-alpine
    # build: ./admin
    ports:
      - "5000:5000"
    networks:
      - web_network
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
    env_file:
      - .env
    working_dir: /app
    entrypoint: ["./entrypoint.sh"]
    command: ["poetry", "run", "flask", "run", "--debug"]
    volumes:
      - ./admin:/app
  
  # Vue service
  client:
    build: ./portal
    container_name: vue-app
    ports:
      - 8080:80
    depends_on:
      - admin
    # Nginx service in Vue app
  nginx-vue:
    image: nginx:alpine
    container_name: nginx-vue-app
    volumes:
      - ./portal/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - client

  # Postgres service
  db:
    container_name: postgres-db
    image: postgres:15
    networks:
      - web_network
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"

# Red entre web y db
networks:
  web_network: